export const TaskGroupsData = [
  {
    id: 1,
    owner: "John Doe",
    code: "1",
    technical_dependencies: "none",
    temporal_dependencies: "crusher1",
    milestone: "",
    computed_task_group_start_date: "2020-01-01",
    computed_task_group_end_date: "2020-01-31",
    total_tasks_duration: "8",
    not_done_tasks_duration: "8",
    completed_tasks_duration: "0",
    status: "0",
    progress: "70",
    start_date_delay: "10",
    name: "Task Group 1",
    end_date_delay: "0",
    description: "Task Group 1 ",
    user_problem: "User Problem 1",
    use_case_category: "Use Case Category 1",
    software_category: "Software Category 1",
    software_subcategory: "Software Subcategory 1",
    note: "Note 1",
    issues_and_unknows: "Issues and Unknowns 1",
    use_case_priority: "Use Case Priority 1"
  },
  {
    id: 2,
    owner: "Mark Twain",
    code: "2",
    technical_dependencies: "crusher1",
    temporal_dependencies: "crusher1",
    milestone: "",
    computed_task_group_start_date: "2020-02-01",
    computed_task_group_end_date: "2020-02-28",
    total_tasks_duration: "8",
    not_done_tasks_duration: "8",
    completed_tasks_duration: "0",
    status: "0",
    progress: "0",
    start_date_delay: "0",
    name: "Task Group 2",
    end_date_delay: "0",
    description: "Task Group 2 ",
    user_problem: "User Problem 2",
    use_case_category: "Use Case Category 2",
    software_category: "Software Category 2",
    software_subcategory: "Software Subcategory 2",
    note: "Note 2",
    issues_and_unknows: "Issues and Unknowns 2",
    use_case_priority: "Use Case Priority 2"
  },
  {
    id: 3,
    owner: "Matia Brown",
    code: "3",
    technical_dependencies: "",
    temporal_dependencies: "",
    milestone: "",
    computed_task_group_start_date: "2020-03-01",
    computed_task_group_end_date: "2020-03-31",
    total_tasks_duration: "8",
    not_done_tasks_duration: "8",
    completed_tasks_duration: "0",
    status: "0",
    progress: "0",
    start_date_delay: "0",
    name: "Task Group 3",
    end_date_delay: "0",
    description: "Task Group 3 ",
    user_problem: "User Problem 3",
    use_case_category: "Use Case Category 3",
    software_category: "Software Category 3",
    software_subcategory: "Software Subcategory 3",
    note: "Note 3",
    issues_and_unknows: "Issues and Unknowns 3",
    use_case_priority: "Use Case Priority 3"
  }
]
